# Generated by Django 4.2.13 on 2024-08-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=150)),
                ('smobile', models.CharField(max_length=15)),
                ('saddress', models.TextField()),
            ],
        ),
    ]
