# Generated by Django 4.2.13 on 2024-08-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='saddress',
            field=models.TextField(verbose_name='Student Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='smobile',
            field=models.CharField(max_length=15, verbose_name='Student Contact Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=150, verbose_name='Name of Student'),
        ),
    ]
